### ISSUE TITLE
Make a meetup in Tel-Aviv!!! on Oct 3rd

### ISSUE THREAD

**Issue by iscander01** [iscander01/testPrivateRepo#229]
in BEAM office!

**Comment by sasha-abramovich** [comment]
Which are the dates? This is very stupid offer!

**Comment by sasha-abramovich** [comment]
I'm sorry I'm thinking about Sept 3rd

**Comment by sasha-abramovich** [comment]
Other user: there was a meeting in Tel-Aviv (see this link)

**Comment by sasha-abramovich** [comment]
Oh that's good, if so, October 3rd (title changed).
